apiVersion: v1
kind: Secret
metadata:
  name: parentinfo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  STORAGE_TYPE: {{ .Values.storageType | quote }}
  DEBUG: {{ .Values.django.secret.debug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.secret.allowedHosts | quote }}
  DJANGO_CSRF_TRUSTED_ORIGINS: {{ .Values.django.secret.csrfTrustedOrigins | quote }}
  DJANGO_SECRET_KEY: {{ .Values.django.secret.secretKey | quote }}
