{{- if eq .Values.storageType "cloud" }}
apiVersion: v1
kind: Secret
metadata:
  name: parentinfo-r2-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  STORAGE_TYPE: "cloud"
  AWS_ACCESS_KEY_ID: {{ .Values.r2.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.r2.secretAccessKey | quote }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.r2.bucketName | quote }}
  AWS_S3_ENDPOINT_URL: {{ .Values.r2.endpointUrl | quote }}
  AWS_S3_CUSTOM_DOMAIN: {{ .Values.r2.customDomain | quote }}
  AWS_S3_REGION_NAME: {{ .Values.r2.regionName | quote }}
{{- end }}
